### ISSUE TITLE
Can't undo after adjust angle of frame by two edges

### ISSUE THREAD

**Issue by cvgaviao** [oddtopus/flamingo#11]
If we select the wrong edge, the adjust angle tool can mess the entire structure.
But the real problem is that pressing the undo won't undo that action. I will need to clear the path and do all adjusts again.

**Comment by oddtopus** [comment]
Ops! I forgot to record the "adjust angle" in the document history, so you were actually undoing the previous command.
Now should work.
Thanks.

**Comment by cvgaviao** [comment]
@oddtopus, there are other functions that has the same problem: "place on beam...", "insert standard sections". 
do I need to create one issue for each one ?
