### ISSUE TITLE
Updating Flamingo WB to be compatible with the upcoming 0.18 release (req. py3 and Qt5 compatibility) 

### ISSUE THREAD

**Issue by luzpaz** [oddtopus/flamingo#15]
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/93

**Comment by Geoplace** [comment]
Hi, There's seems a bug in the recent v18 freecad. If you made somo correction I can test it to see if it work's again. 

1.- Open FreeCad v18.
2.- Select Flamingo Workbench.
3.- The workbench didn’t load. Here is the Report and Console Output.

Report View:
invalid syntax (CommandsSpSh.py, line 38)
Traceback (most recent call last):
File "<string>", line 110, in Initialize

![image](https://user-images.githubusercontent.com/8289274/54624336-cd052f00-4a32-11e9-8c84-79a0e746fac9.png)

OS: Windows 8.1
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16093 (Git)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 690774c0effe4fd7b8d2b5e2fb2b8c8d145e21ce
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Spanish/Mexico (es_MX)

**Comment by luzpaz** [comment]
@oddtopus I'm going to close this ticket as dodo succeeds flamingo for py3/qt5 right?
@Geoplace I don't think this is the appropriate place for you to post this issue. Better to have created a separate issue for it.

**Comment by oddtopus** [comment]
That's ok, thanks.

Il giorno lun 16 set 2019 alle ore 15:24 luzpaz <notifications@github.com>
ha scritto:

**Comment by luzpaz** [comment]
Note: @Geoplace that dodo is the py3/Qt5 replacement for flamingo. You're running py3/qt5 dependencies. So try dodo workbench

**Comment by Geoplace** [comment]
Thank you. i would give Dodo a try.  
Regards
