### ISSUE TITLE
Move out of FC wiki 'Sandbox' and also mention on FC 0.17 release page

### ISSUE THREAD

**Issue by luzpaz** [oddtopus/flamingo#7]
I think a small blurb with an animated gif and a link to the [flamingo wiki page](https://www.freecadweb.org/wiki/Sandbox:Flamingo) (which is currenty in the Sandbox still)
on https://www.freecadweb.org/wiki/Release_notes_017#Additional_Modules

Thoughts?

**Comment by oddtopus** [comment]
Dear @luzpaz,
I'd like to move that wiki out of the sandbox but I don't know how.
I'm a newby with wiki stuff [(see here)](https://forum.freecadweb.org/viewtopic.php?t=23555) so can you give me an advice or tell me where I can find the instructions?
Thanks

**Comment by luzpaz** [comment]
@oddtopus I'll see what I can do :wink: 
I need to be mindful how I do this, previously I moved a page and it broke its translations (I also changed the title of it, so I think that was the extra layer of complexity that made the translations break)

**Comment by luzpaz** [comment]
@oddtopus can I rename the page to **Flamingo Workbench** ?

**Comment by oddtopus** [comment]
> can I rename the page to Flamingo Workbench ?

Sure! And thanks for your help.

**Comment by luzpaz** [comment]
Done! 
Took care of the links on the 0.17 Release page
