### ISSUE TITLE
pipeCmd.join() does not remove port marks on deleted objects

### ISSUE THREAD

**Issue by rkrenzler** [oddtopus/flamingo#8]
How to reproduce:

1. Create new document.
2. Insert a pipe.
3. Click on the button which joins fittings (pipeCmd.join() command).
4. Select the pipe. Green triangles apear on both sides of the pipe.
5. Delete the pipe.
6. The pipe is deleted but the green triangles are still there.

**Comment by oddtopus** [comment]
Press ESC before deleting the pipe.
That terminates the observer class neatly and remove both the callbacks and
the pure graphical elements.
I know it's tricky to deal with that. Just remember that the arrows are
independent objects that do not have a Shape and Geometry like other solids
displayed but are only graphics sketched in the view-scene (check "Inventor
Mentor" for more about that).
Anyway, if something fails or you forget to press ESC, when you save and
close the document the arrows disappear.

2018-04-01 12:32 GMT+02:00 rkrenzler <notifications@github.com>:

**Comment by rkrenzler** [comment]
Thanks for the explanation. I will try to find out, if it is possible to clean up this kind of objects.
Sometimes the command crashes and leaves the arrows too.

**Comment by oddtopus** [comment]
Added dialog (with "reset" button). Thus by leaving it, all the arrows will be closed neatly.
